In [1]:
import pandas as pd
from tools.transformer import TabularTransformer

In [2]:
import plotly.express as px
# import plotly.graph_objs as go
# from plotly.offline import init_notebook_mode

In [ ]:
%load_ext autoreload
%autoreload 2

In [3]:
df = pd.read_csv("data/data.csv")

In [4]:
# filtering prices
df = df.loc[(df["PRICE"] > 0) & (df["PRICE"] < 2500), :]

In [5]:
df

,ID_PRODUCT,ID_UNIVERSE,ID_CATEGORY,ID_SUBCAT,ID_SUB_SUBCAT,ID_BRAND,ID_MODEL,ID_COLOR,ID_MATERIAL,ID_MATERIAL_TYPE,...,ID_SIZE_TYPE,GEO2_SELLER,HOURS_ONLINE,ORDER_CURRENCY,DATE_SOLD,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,PRICE
0,7749612,1,12,137,0,50,0,14,18,0,...,7,us,10167,sgd,2020-08-18,2020,8,18,2,2067
1,3247136,1,13,510,0,57,0,3,3,0,...,38,soe,32942,gbp,2020-08-21,2020,8,21,5,113
2,11459455,1,141,527,216,2,0,9,4,0,...,0,soe,133,usd,2020-08-26,2020,8,26,3,298
3,11117985,2,12,37,139,47,0,223,1,0,...,147,roe,775,usd,2020-08-18,2020,8,18,2,133
4,9775312,2,13,605,0,102,0,14,3,0,...,56,soe,3206,eur,2020-08-03,2020,8,3,1,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175110,14904470,1,12,80,10,2731,0,9,2,0,...,7,us,194,usd,2021-03-19,2021,3,19,5,21
175111,13969831,1,13,510,0,6,4114,225,4,0,...,34,france,1939,usd,2021-04-12,2021,4,12,1,147
175112,10478404,2,14,54,0,6444,0,3,46,0,...,106,soe,172,eur,2020-06-01,2020,6,1,1,95
175113,13136038,1,141,59,197,57,0,2,16,0,...,0,roe,104,eur,2020-12-06,2020,12,6,0,241
175114,11204374,1,13,506,0,60,0,9,19,0,...,39,soe,1144,eur,2020-09-11,2020,9,11,5,125

In [ ]:
px.histogram(df, x="PRICE", title="Histogram")

In [6]:
from sklearn.preprocessing import PowerTransformer

pow_trans = PowerTransformer(method="box-cox")

In [7]:
df["PRICE_NORM"] = pow_trans.fit_transform(df["PRICE"].values.reshape(len(df), 1)).flatten()

In [ ]:
px.histogram(df, x="PRICE_NORM", title="Histogram")

In [ ]:
df.columns

In [8]:
tt = TabularTransformer(
    numeric=["HOURS_ONLINE"],
    dates=["DATE_SOLD"],
    ordinal=["ID_UNIVERSE", "ID_CATEGORY", "ID_SUBCAT", "ID_SUB_SUBCAT", "ID_BRAND", "ID_MODEL", "ID_COLOR", "ID_MATERIAL", "ID_MATERIAL_TYPE", "ID_CONDITION", "VINTAGE", "ID_BRACELET", "ID_BOX", "ID_MECHANISM", "ID_SIZE_TYPE", "GEO2_SELLER", "ORDER_CURRENCY"], # ordinal
    cat=[], # one-hot
    highcat=[]
)

In [9]:
input_list = tt.fit_transform(df)

In [10]:
len(input_list)

173756

In [ ]:
# print([(item.shape, item.dtype) for item in input_list])

In [11]:
df_transformed = pd.DataFrame(input_list, columns=tt.columns)
# df_transformed[tt.columns[1][0]] = input_list[1]
# df_transformed[tt.columns[1][1]] = input_list[2]

In [12]:
df_transformed

,HOURS_ONLINE,DATE_SOLD_day_sin,DATE_SOLD_day_cos,DATE_SOLD_dayofweek_sin,DATE_SOLD_dayofweek_cos,DATE_SOLD_month_sin,DATE_SOLD_month_cos,DATE_SOLD_year,ID_UNIVERSE,ID_CATEGORY,...,ID_MATERIAL,ID_MATERIAL_TYPE,ID_CONDITION,VINTAGE,ID_BRACELET,ID_BOX,ID_MECHANISM,ID_SIZE_TYPE,GEO2_SELLER,ORDER_CURRENCY
0,1.371857,-0.485302,-0.874347,8.660254e-01,0.5,-8.660254e-01,-5.000000e-01,0.5,1.0,1.0,...,10.0,0.0,2.0,0.0,0.0,0.0,0.0,201.0,11.0,10.0
1,2.152507,-0.897805,-0.440394,-8.660254e-01,-0.5,-8.660254e-01,-5.000000e-01,0.5,1.0,2.0,...,23.0,0.0,2.0,0.0,0.0,0.0,0.0,164.0,9.0,5.0
2,-0.582988,-0.848644,0.528964,8.660254e-01,-0.5,-8.660254e-01,-5.000000e-01,0.5,1.0,4.0,...,32.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0,9.0,11.0
3,0.070282,-0.485302,-0.874347,8.660254e-01,0.5,-8.660254e-01,-5.000000e-01,0.5,2.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,34.0,7.0,11.0
4,0.701538,0.571268,0.820763,0.000000e+00,1.0,-8.660254e-01,-5.000000e-01,0.5,2.0,2.0,...,23.0,0.0,2.0,0.0,0.0,0.0,0.0,185.0,9.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173751,-0.446546,-0.651372,-0.758758,-8.660254e-01,-0.5,1.000000e+00,6.123234e-17,1.0,1.0,1.0,...,12.0,0.0,2.0,0.0,0.0,0.0,0.0,201.0,11.0,11.0
173752,0.467195,0.651372,-0.758758,0.000000e+00,1.0,8.660254e-01,-5.000000e-01,1.0,1.0,2.0,...,32.0,0.0,6.0,0.0,0.0,0.0,0.0,160.0,3.0,11.0
173753,-0.489119,0.201299,0.979530,0.000000e+00,1.0,1.224647e-16,-1.000000e+00,0.5,2.0,3.0,...,39.0,0.0,1.0,0.0,0.0,0.0,0.0,9.0,9.0,4.0
173754,-0.660324,0.937752,0.347305,-2.449294e-16,1.0,-2.449294e-16,1.000000e+00,0.5,1.0,4.0,...,8.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,7.0,4.0
173755,0.231576,0.790776,-0.612106,-8.660254e-01,-0.5,-1.000000e+00,-1.836970e-16,0.5,1.0,2.0,...,11.0,0.0,6.0,0.0,0.0,0.0,0.0,165.0,9.0,4.0

In [18]:
# adding PRICE data
df_transformed["PRICE"] = df["PRICE"]
df_transformed["ID_PRODUCT"] = df["ID_PRODUCT"]

df_transformed

,HOURS_ONLINE,DATE_SOLD_day_sin,DATE_SOLD_day_cos,DATE_SOLD_dayofweek_sin,DATE_SOLD_dayofweek_cos,DATE_SOLD_month_sin,DATE_SOLD_month_cos,DATE_SOLD_year,ID_UNIVERSE,ID_CATEGORY,...,ID_CONDITION,VINTAGE,ID_BRACELET,ID_BOX,ID_MECHANISM,ID_SIZE_TYPE,GEO2_SELLER,ORDER_CURRENCY,PRICE,ID_PRODUCT
0,1.371857,-0.485302,-0.874347,8.660254e-01,0.5,-8.660254e-01,-5.000000e-01,0.5,1.0,1.0,...,2.0,0.0,0.0,0.0,0.0,201.0,11.0,10.0,2067.0,7749612.0
1,2.152507,-0.897805,-0.440394,-8.660254e-01,-0.5,-8.660254e-01,-5.000000e-01,0.5,1.0,2.0,...,2.0,0.0,0.0,0.0,0.0,164.0,9.0,5.0,113.0,3247136.0
2,-0.582988,-0.848644,0.528964,8.660254e-01,-0.5,-8.660254e-01,-5.000000e-01,0.5,1.0,4.0,...,4.0,1.0,0.0,0.0,0.0,0.0,9.0,11.0,298.0,11459455.0
3,0.070282,-0.485302,-0.874347,8.660254e-01,0.5,-8.660254e-01,-5.000000e-01,0.5,2.0,1.0,...,1.0,0.0,0.0,0.0,0.0,34.0,7.0,11.0,133.0,11117985.0
4,0.701538,0.571268,0.820763,0.000000e+00,1.0,-8.660254e-01,-5.000000e-01,0.5,2.0,2.0,...,2.0,0.0,0.0,0.0,0.0,185.0,9.0,4.0,75.0,9775312.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173751,-0.446546,-0.651372,-0.758758,-8.660254e-01,-0.5,1.000000e+00,6.123234e-17,1.0,1.0,1.0,...,2.0,0.0,0.0,0.0,0.0,201.0,11.0,11.0,70.0,11205168.0
173752,0.467195,0.651372,-0.758758,0.000000e+00,1.0,8.660254e-01,-5.000000e-01,1.0,1.0,2.0,...,6.0,0.0,0.0,0.0,0.0,160.0,3.0,11.0,92.0,12006533.0
173753,-0.489119,0.201299,0.979530,0.000000e+00,1.0,1.224647e-16,-1.000000e+00,0.5,2.0,3.0,...,1.0,0.0,0.0,0.0,0.0,9.0,9.0,4.0,137.0,9043601.0
173754,-0.660324,0.937752,0.347305,-2.449294e-16,1.0,-2.449294e-16,1.000000e+00,0.5,1.0,4.0,...,2.0,0.0,0.0,0.0,0.0,0.0,7.0,4.0,81.0,10948183.0
173755,0.231576,0.790776,-0.612106,-8.660254e-01,-0.5,-1.000000e+00,-1.836970e-16,0.5,1.0,2.0,...,6.0,0.0,0.0,0.0,0.0,165.0,9.0,4.0,500.0,10288209.0

In [20]:
df_transformed.to_csv("data/data_encoded.csv", index=False)